[package]
name = "kachina-installer"
version = "0.1.0"
description = "Unified installer and upgrader"
authors = ["YuehaiTeam"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["unstable"] }
tauri-plugin-opener = "2"
tauri-plugin-fs = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
async-compression = { version = "0.4", features = ["tokio", "zstd"] }
tokio = { version = "1", features = ["full"] }
chksum-md5 = { version = "0.1", features = [
    "reader",
    "writer",
    "async-runtime-tokio",
] }
reqwest = { version = "0.12", default-features = false, features = [
    "http2",
    "json",
    "rustls-tls-native-roots",
    "charset",
    "gzip",
    "brotli",
    "zstd",
    "stream",
] }
futures = "0.3"
tokio-util = "0.7"
async-walkdir = "2.0"
tauri-plugin-dialog = "2"
winreg = "0.52"
windows = { version = "0.58", features = ["Win32_System_Console"] }
rfd = "0.15"
nt_version = "0.1"
lazy_static = "1.5"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tracing = "0.1.41"

[profile.release]
codegen-units = 1 # Allows LLVM to perform better optimization.
lto = true        # Enables link-time-optimizations.
opt-level = "s"   # Prioritizes small binary size. Use `3` if you prefer speed.
panic = "abort"   # Higher performance by disabling panic handlers.
strip = true      # Ensures debug symbols are removed.
